### ISSUE TITLE
File upload/download

### ISSUE THREAD

**Issue by freitasjuciel** [hnordt/flow#4]

**Comment by hnordt** [comment]
Acredito que isso não tem muito segredo, precisamos apenas de um componente React como `<FileInput />` e vamos disparar uma requisição normalmente.

Esse caso entra num caso tão comum quanto atualizar um campo de texto e enviar esse dado para o servidor, a diferença é que no caso de arquivos trabalhamos bom blobs e não com texto.

**Comment by freitasjuciel** [comment]
Sim, foi o que imaginei mesmo
