### ISSUE TITLE
Toggle - Sidebar

### ISSUE THREAD

**Issue by globsecure** [hnordt/flow#5]
Opção de controlar o sidebar de modo que o estado seja global e passivo de mudança pelos componentes.

1. Sidebar esquerdo com menu
2. Sidebar direito com notificações, chat e outros.

**Comment by hnordt** [comment]
Acho que nesse caso não devemos reinventar a roda e podemos seguir o que a documentação do Redux sugere em Organizing Normalized Data in State (https://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html#organizing-normalized-data-in-state).

Teríamos um uiReducer:

```js
const initialState = {
  leftSidebar: {
    isVisible: true
  },
  rightSidebar: {
    isVisible: false,
    notificationCount: 0
  }
}

const uiReducer = (state = initialState, action) => {
  if (action.type === TOGGLE_LEFT_SIDEBAR)
    return {
      ...state,
      leftSidebar: {
        ...state.leftSidebar,
        isVisible: !state.leftSidebar.isVisible
      }
    }

  if (action.type === RECEIVE_INSTANT_MESSAGE)
    return {
      ...state,
      rightSidebar: {
        ...state.rightSidebar,
        notificationCount: state.rightSidebar.notificationCount + 1
      }
    }


  return state
}
```

Caso esse reducer crescer muito, podemos dividir em subreducers.
