### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by schuchowsky** [hnordt/flow#6]
How would we render a login error, such as "Invalid credentials"?

```
<Flow
  id={LOGIN_FLOW}
  render={({ isPending, startFlow }) => (
    <Form isLoading={isPending} onSubmit={startFlow} />
  )}
/>
```

**Comment by hnordt** [comment]
Esse é mais um caso em que não vamos reinventar a roda.

Temos uma action `showNotification()` e o `loginFlow()` dispara essa action em caso de erro. Então temos um componente global `<Notifcations />` que lê os erros no store e exibe o componente relevante, juntamente com um trigger pra `hideNotification`, e.g.:

```js
const Notifications = () => (
  <Store
    render={({ state, dispatch }) =>
      getNotifications().map(({ id, intent, iconName, title, message }) => (
        <Alert
          key={id}
          intent={intent}
          iconName={iconName}
          message={message}
          onClosePress={() => dispatch(hideNotification(id))}
        />
      ))
    }
  />
)
```

`showNotification`, `hideNotification`, `getNotifications` e `notificationsReducer` são genéricos o suficiente para serem distribuídos dentro de um pacote no npm, porém o componente Notifications vai ser criado por projeto.

**Comment by schuchowsky** [comment]
Sounds good.
