### ISSUE TITLE
"Global Filter" use case

### ISSUE THREAD

**Issue by schuchowsky** [hnordt/flow#9]
There's a global state - in this case: `currentNetwork`.

Changing this global state should update some data, according to the current screen.

Each screen should so something different, when changing the `currentNetwork`.

In the example below, changing the `currentNetwork` should update the data of the chart.

![](https://d.pr/i/L0mzN4+)

**Comment by hnordt** [comment]
`currentNetwork` vai ser armazenada no `uiReducer`, conforme explicado em https://github.com/hnordt/flow/issues/5, porque ela é um state da UI.

Quando o usuario selecionar uma nova network, iniciamos `updateCurrentNetworkFlow()`. Esse flow irá disparar novas requisições, a resposta destas requisições serão processadas pelo entitiesReducer, e então como suas views usam `<Entity />` ou `<Store />` pra ler os dados, elas serão atualizadas automaticamente.

Pra atualizar `currentNetwork` você pode ler `action.type === START_FLOW && flowId === UPDATE_CURRENT_NETWORK_FLOW` dentro do `uiReducer`.

**Comment by schuchowsky** [comment]
Got it.
